### ISSUE TITLE
How does this improve from Obsidian Importer?

### ISSUE THREAD

**Issue by Sire** [senselogic/OBSIDION#1]
What benefits does this have compared to the very actively developed (semi official) plugin?

https://github.com/obsidianmd/obsidian-importer

**Comment by SenseLogic** [comment]
Yes I know about this one, I actually used it first to import my 2G+ of Notion notes inside Obsidian.

Unfortunately it was not adapted at all to my own use case.

I needed one which not only renames all notes and links to remove the UUID garbage, but also cleans all notes from the sub-page links, since they are automatically generated by my Atlas plugin, in order to replicate as much as possible the Notion look and feel within Obsidian.

So if you don't plan to use Obsidian in a Notion-like manner, my guess is that you should probably stick to the official plugin.
